name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache Rust Cargo
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build Tauri Application
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-app
          path: |
            ./src-tauri/target/release/*.deb
            ./src-tauri/target/release/*.AppImage
            ./src-tauri/target/release/*.dmg
            ./src-tauri/target/release/*.exe
